# app/config/security.yml
security:
    encoders:
        RSS\AdminBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: RSSAdminBundle:User }
        in_memory:
            memory:
                users:
                    user:  { password: rhino, roles: [ 'ROLE_USER' ] }
                    admin: { password: applehouse, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        main:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /
        admin_area:
            pattern:    ^/admin
            http_basic: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/tags, roles: ROLE_ADMIN }