RSS\ReaderBundle\Entity\Rss:
    type: entity
    table: rss
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: text
            nullable: false
        url:
            type: text
            nullable: false
        createDate:
            type: date
            nullable: false
            column: create_date
        updateDate:
            type: date
            nullable: false
            column: update_date
    lifecycleCallbacks: {  }
